server:
  port: 8080

spring:
  application:
    name: Celebrities

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Shriganesh@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
